/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/admin`; params?: Router.UnknownInputParams; } | { pathname: `/admin/inventory`; params?: Router.UnknownInputParams; } | { pathname: `/admin/inventory_mgmt`; params?: Router.UnknownInputParams; } | { pathname: `/admin/orders`; params?: Router.UnknownInputParams; } | { pathname: `/admin/recent`; params?: Router.UnknownInputParams; } | { pathname: `/admin/settings`; params?: Router.UnknownInputParams; } | { pathname: `/buyer`; params?: Router.UnknownInputParams; } | { pathname: `/worker`; params?: Router.UnknownInputParams; } | { pathname: `/admin/order/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/admin`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/inventory`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/inventory_mgmt`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/orders`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/recent`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/buyer`; params?: Router.UnknownOutputParams; } | { pathname: `/worker`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/order/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/admin${`?${string}` | `#${string}` | ''}` | `/admin/inventory${`?${string}` | `#${string}` | ''}` | `/admin/inventory_mgmt${`?${string}` | `#${string}` | ''}` | `/admin/orders${`?${string}` | `#${string}` | ''}` | `/admin/recent${`?${string}` | `#${string}` | ''}` | `/admin/settings${`?${string}` | `#${string}` | ''}` | `/buyer${`?${string}` | `#${string}` | ''}` | `/worker${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/admin`; params?: Router.UnknownInputParams; } | { pathname: `/admin/inventory`; params?: Router.UnknownInputParams; } | { pathname: `/admin/inventory_mgmt`; params?: Router.UnknownInputParams; } | { pathname: `/admin/orders`; params?: Router.UnknownInputParams; } | { pathname: `/admin/recent`; params?: Router.UnknownInputParams; } | { pathname: `/admin/settings`; params?: Router.UnknownInputParams; } | { pathname: `/buyer`; params?: Router.UnknownInputParams; } | { pathname: `/worker`; params?: Router.UnknownInputParams; } | `/admin/order/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/admin/order/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
